### ISSUE TITLE
Could this proposal be misused to workaround private fields brand checks?

### ISSUE THREAD

**Issue by nicolo-ribaudo** [littledan/proposal-class-initialize#2]
```js
class A {
  #brand;
  foo() { this.#brand; }
}

var obj = {};
A.prototype.foo.call(obj); // throws

initialize(obj, A);

A.prototype.foo.call(obj); // works?

function initialize(obj, Class) {
  new class extends Class {
    constructor() {
      class.initialize(obj); // This installs the private fields, right?
    }
  }
}
```

If this is possible, brand checks would become much more less useful from a security point of view.

**Comment by littledan** [comment]
That example won't work. It doesn't install the private fields from inherited classes, only from that class itself.

The idea here is, it's up to the class to decide who to install private fields on. If you decide to install your own private fields on some other object, you're deciding to grant your brand to it. This proposal doesn't add any fundamental power to the addition of private fields, as you can already accomplish this sort of thing with the super return trick. For that reason, I can't think of any guarantees it would weaken.

**Comment by nicolo-ribaudo** [comment]
Thank you for the explanation

**Comment by littledan** [comment]
Added an explanation to the readme.
